### ISSUE TITLE
v10 errors

### ISSUE THREAD

**Issue by strongpauly** [trioderegion/dnd5e-helpers#308]
Errors appear in the console when attempting to use this module in v10 Release 10.284:

```
foundry.js:711 TypeError: Cannot read properties of undefined (reading 'effects')
[Detected 1 package: dnd5e-helpers]
    at Token5e.drawEffect (ActionManagement.js:542:27)
    at async Promise.all (index 0)
    at async Token5e.drawEffects (foundry.js:45715:7)
    at async Token5e._draw (foundry.js:45384:5)
    at async Token5e.draw (foundry.js:24869:5)
    at async Promise.all (index 0)
    at async TokenLayer._draw (foundry.js:30452:5)
    at async TokenLayer._draw (foundry.js:36466:5)
    at async TokenLayer.draw (foundry.js:29972:5)
    at async InterfaceCanvasGroup.draw (foundry.js:28407:9)
    at async InterfaceCanvasGroup.draw (foundry.js:38649:5)
    at async Canvas.draw (foundry.js:23403:11)
    at async Scene.view (foundry.js:20727:7)
    at async Game.initializeCanvas (foundry.js:7909:20)
    at async Game.setupGame (foundry.js:7747:5)
    at async Game._initializeGameView (foundry.js:8820:5)
    at async Game.initialize (foundry.js:7630:5)
```

```
foundry.js:711 TypeError: Cannot set properties of null (setting 'visible')
[No packages detected]
    at SoundsLayer._deactivate (foundry.js:30510:26)
    at SoundsLayer.deactivate (foundry.js:30096:10)
    at TokenLayer.activate (foundry.js:30061:76)
    at Canvas.#initializeCanvasLayer (foundry.js:23575:11)
    at Canvas.#initialize (foundry.js:23525:32)
    at Canvas.draw (foundry.js:23419:29)
    at async Scene.view (foundry.js:20727:7)
    at async Game.initializeCanvas (foundry.js:7909:20)
    at async Game.setupGame (foundry.js:7747:5)
    at async Game._initializeGameView (foundry.js:8820:5)
    at async Game.initialize (foundry.js:7630:5)
```

**Comment by trioderegion** [comment]
We have no v10 compatible version at this time.

**Comment by strongpauly** [comment]
I appreciate it's your repository and you can manage your issues however you like, and believe me I know how nice it is to remove clutter.  However, it might be a better way to document what you're planning to label these bugs as issues as planned for v10 or something, rather than closing.  This way people have visibility.

If you have no intention of ever supporting v10 this would also be good to know so people can start looking for alternative solutions.

**Comment by shecrio** [comment]
fun fact, if you turn off Reflow Effects in configuration this error stops happening and you go to just it not working instead of it breaking the canvas.
